services:
  mariadb:
    image: mariadb:10.11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:v5.25.8
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      - ../semgrep-rules:/workspace/semgrep-rules
      - frappe-bench-data:/home/frappe/frappe-bench
    ports:
      - 8000:8000
      - 9000:9000

volumes:
  mariadb-data:
  frappe-bench-data:
